### ISSUE TITLE
Register the ApplicationEventListener via spring.factories

### ISSUE THREAD

**Issue by filiphr** [coders-kitchen/spring-boot-multi-module-property-files#1]
This is something which I really needed and I found your example really good. However, I didn't like the registration of the application listener in the main module.

You can avoid the explicit registration if you provide a `META-INF/spring.factories` with `org.springframework.context.ApplicationListener=com.example.project.MyListener`. Have a look here [spring-boot-features#application-events-and-listeners](
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc#application-events-and-listeners).

Are you accepting PRs?

**Comment by coders-kitchen** [comment]
Hey,

great to hear that it is useful for you.

Cool, if haven't came across that yet. It's definitely a better way to provide it. 
And I would be happy to see a PR :)
